// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation.proto

package com.sbt.validation.proto;

/*-
 * #%L
 * Protobuf validator
 * %%
 * Copyright (C) 2017 - 2019 Entur AS and original authors
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
public final class Validation {
  private Validation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Validation.max);
    registry.add(Validation.min);
    registry.add(Validation.past);
    registry.add(Validation.future);
    registry.add(Validation.repeatMax);
    registry.add(Validation.repeatMin);
    registry.add(Validation.regex);
    registry.add(Validation.required);
    registry.add(Validation.forbidden);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int MAX_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Long> max = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Long.class,
        null);
  public static final int MIN_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Long> min = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Long.class,
        null);
  public static final int PAST_FIELD_NUMBER = 50003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> past = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int FUTURE_FIELD_NUMBER = 50004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> future = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int REPEATMAX_FIELD_NUMBER = 50005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Long> repeatMax = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Long.class,
        null);
  public static final int REPEATMIN_FIELD_NUMBER = 50006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Long> repeatMin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Long.class,
        null);
  public static final int REGEX_FIELD_NUMBER = 50007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> regex = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int REQUIRED_FIELD_NUMBER = 50008;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> required = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int FORBIDDEN_FIELD_NUMBER = 50009;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> forbidden = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020validation.proto\022\nvalidation\032 google/p" +
      "rotobuf/descriptor.proto:,\n\003max\022\035.google" +
      ".protobuf.FieldOptions\030\321\206\003 \001(\003:,\n\003min\022\035." +
      "google.protobuf.FieldOptions\030\322\206\003 \001(\003:-\n\004" +
      "past\022\035.google.protobuf.FieldOptions\030\323\206\003 " +
      "\001(\010:/\n\006future\022\035.google.protobuf.FieldOpt" +
      "ions\030\324\206\003 \001(\010:2\n\trepeatMax\022\035.google.proto" +
      "buf.FieldOptions\030\325\206\003 \001(\003:2\n\trepeatMin\022\035." +
      "google.protobuf.FieldOptions\030\326\206\003 \001(\003:.\n\005" +
      "regex\022\035.google.protobuf.FieldOptions\030\327\206\003" +
      " \001(\t:1\n\010required\022\035.google.protobuf.Field" +
      "Options\030\330\206\003 \001(\010:2\n\tforbidden\022\035.google.pr" +
      "otobuf.FieldOptions\030\331\206\003 \001(\010B\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    max.internalInit(descriptor.getExtensions().get(0));
    min.internalInit(descriptor.getExtensions().get(1));
    past.internalInit(descriptor.getExtensions().get(2));
    future.internalInit(descriptor.getExtensions().get(3));
    repeatMax.internalInit(descriptor.getExtensions().get(4));
    repeatMin.internalInit(descriptor.getExtensions().get(5));
    regex.internalInit(descriptor.getExtensions().get(6));
    required.internalInit(descriptor.getExtensions().get(7));
    forbidden.internalInit(descriptor.getExtensions().get(8));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
